Repository dmytro-komlyk/landing-tda-consulting, pull requests merged in 2023-01, with the labels that each got.

#1 Fix name error
  package.json
Labels: documentation

#2 Patch/content/areas activity
  src/images/areas-activity.png
  src/index.html
  src/styles/modules/_areas-activity.scss
  src/styles/modules/_banner.scss
  src/styles/modules/_header.scss
  src/styles/modules/_main.scss
Labels: enhancement

#3 Changed nav styles. Added switch language button
  package-lock.json
  src/index.html
  src/styles/_common.scss
  src/styles/_variables.scss
  src/styles/modules/_header.scss
  src/styles/modules/_main.scss
Labels: enhancement

#4 Update/content/banner
  src/index.html
  src/styles/_atoms.scss
  src/styles/_common.scss
  src/styles/modules/_banner.scss
  src/styles/modules/_header.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
  src/styles/styles.scss
Labels: enhancement

#5 Feature/body
  src/index.html
  src/styles/_atoms.scss
  src/styles/_common.scss
  src/styles/modules/_banner.scss
  src/styles/modules/_header.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
  src/styles/styles.scss
Labels: enhancement

#6 Feature/body
  package-lock.json
  src/index.html
  src/styles/_atoms.scss
  src/styles/_common.scss
  src/styles/_variables.scss
  src/styles/modules/_banner.scss
  src/styles/modules/_header.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
  src/styles/styles.scss
Labels: enhancement

#7 Path/content/contact
  package-lock.json
  src/index.html
  src/styles/_atoms.scss
  src/styles/modules/_contacts.scss
  src/styles/styles.scss
Labels: enhancement

#9 Feature/body
  package-lock.json
  src/index.html
  src/styles/_atoms.scss
  src/styles/modules/_contacts.scss
  src/styles/styles.scss
Labels: enhancement

#10 Fix/layout
  src/index.html
  src/styles/modules/_areas-activity.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
Labels: bug

#11 Feature/body
  src/index.html
  src/styles/modules/_areas-activity.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
Labels: bug

#12 Patch/content/photogallery
  src/images/team.jpg
  src/images/w01.jpg
  src/images/w02.jpg
  src/images/w03.jpg
  src/images/w05.jpg
  src/images/w06.jpg
  src/images/w07.jpg
  src/images/w08.jpg
  src/images/w09.jpg
  src/images/w10.jpg
  src/images/w11.jpg
  src/images/w12.jpg
  src/images/w13.jpg
  src/images/w14.jpg
  src/images/w15.jpg
  src/images/w16.jpg
  src/images/w17.jpg
  src/images/w18.jpg
  src/images/w19.jpg
  src/images/w20.jpg
  src/images/w22.jpg
  src/images/w23.jpg
  src/images/w24.jpg
  src/images/w25.jpg
  src/index.html
  src/styles/_atoms.scss
  src/styles/_common.scss
  src/styles/_variables.scss
  src/styles/modules/_areas-activity.scss
  src/styles/modules/_contacts.scss
  src/styles/modules/_header.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
  src/styles/modules/_our-services.scss
  src/styles/modules/_photogallery.scss
  src/styles/styles.scss
Labels: enhancement

#13 Feature/body
  src/images/team.jpg
  src/images/w01.jpg
  src/images/w02.jpg
  src/images/w03.jpg
  src/images/w05.jpg
  src/images/w06.jpg
  src/images/w07.jpg
  src/images/w08.jpg
  src/images/w09.jpg
  src/images/w10.jpg
  src/images/w11.jpg
  src/images/w12.jpg
  src/images/w13.jpg
  src/images/w14.jpg
  src/images/w15.jpg
  src/images/w16.jpg
  src/images/w17.jpg
  src/images/w18.jpg
  src/images/w19.jpg
  src/images/w20.jpg
  src/images/w22.jpg
  src/images/w23.jpg
  src/images/w24.jpg
  src/images/w25.jpg
  src/index.html
  src/styles/_atoms.scss
  src/styles/modules/_main.scss
  src/styles/modules/_photogallery.scss
  src/styles/styles.scss
Labels: duplicate

#17 Feature/body
  gulpfile.js
  package-lock.json
  package.json
  src/images/Dosujy.jpg
  src/images/Drokin.jpg
  src/images/Jovtobruch.jpg
  src/images/Korotinskiy.jpg
  src/images/Kovtun.jpg
  src/images/fidic.jpg
  src/images/smet1.jpg
  src/images/smet2.jpg
  src/images/smet3.jpg
  src/index.html
  src/javascript/index.js
  src/styles/_atoms.scss
  src/styles/_variables.scss
  src/styles/modules/_about-us.scss
  src/styles/modules/_contacts.scss
  src/styles/modules/_footer.scss
  src/styles/modules/_header.scss
  src/styles/modules/_intro.scss
  src/styles/modules/_main.scss
  src/styles/modules/_our-services.scss
  src/styles/modules/_photogallery.scss
  src/styles/styles.scss
Labels: enhancement

#20 Feature/body
  favicon.png
  gulpfile.js
  package-lock.json
  package.json
  src/index.html
  src/styles/modules/_about-us.scss
  src/styles/modules/_contacts.scss
  src/styles/modules/_our-services.scss
Labels: enhancement
